server:
  port: 51802
spring:
  application:
    name: heima-leadnews-article
  cloud:
    nacos:
      discovery:
        # nacos服务注册中心地址
        server-addr: 192.168.110.133:8848
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.110.133:8848
        group: DEFAULT_GROUP
        file-extension: yaml
        username: nacos
        password: nacos
        shared-configs:
          - data-id: heima-leadnews-shared-seata.yaml
      server-addr: 192.168.110.133:8848
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}