server:
  port: 6001
spring:
  application:
    name: heima-leadnews-admin-gateway
  cloud:
    nacos:
      discovery:
        # nacos服务注册中心地址
        server-addr: 192.168.110.133:8848
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.110.133:8848
        group: DEFAULT_GROUP
        file-extension: yaml
        username: nacos
        password: nacos
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}