server:
  port: 8090

spring:
  application:
    name: weather-eureka-client-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#测试
zuul:
  routes:
    hi:
      path: /hi/**
      serviceId: weather-eureka-client
    #城市服务API接口
    city:
      path: /city/**
      serviceId: weather-city-eureka
    #数据服务API接口
    data:
      path: /data/**
      serviceId: weather-data-eureka