spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    hikari:
      username: root
      password: root
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 指定namespace和集群名称
        # namespace: 0e476738-24cb-4ae7-bfec-bd54b9e603ef
        # 假设位于兰州机房
        cluster-name: BJ
        metadata:
          instance: a
          version: V1
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        input:
          # 用来指定topic
          destination: add-bonus
          # 一定要设置
          group: binder-group

  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: user-center
  zipkin:
    base-url: http://localhost:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率，默认0.1
      probability: 1.0

server:
  port: 8081

logging:
  level:
    com.alibaba.nacos: error
    org.springframework.cloud.sleuth: debug

jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600