spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    hikari:
      username: root
      password: root
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  zipkin:
    base-url: http://localhost:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率，默认0.1
      probability: 1.0

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        cluster-name: LZ
    sentinel:
      filter:
        # 打开/关闭掉对Spring MVC端点的保护
        enabled: true
      transport:
        # 指定sentinel 控制台的地址
        dashboard: localhost:8080
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
        bindings:
          output:
            producer:
              transactional: true
              group: tx-add-bonus-group
      bindings:
        output:
          # 用来指定topic
          destination: add-bonus

  main:
    allow-bean-definition-overriding: true

  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: content-center

server:
  port: 8010

#user-center:
  ##  ribbon:
  ##    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#ribbon开启饥饿加载，默认懒加载
ribbon:
  eager-load:
    enabled: true
    clients: user-center

logging:
  level:
    qqzsh.top.contentcenter.feignclient.UserCenterFeignClient: debug
    com.alibaba.nacos: error
    qqzsh.top.contentcenter.dao.content: debug

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        requestInterceptors:
          - qqzsh.top.contentcenter.feignclient.interceptor.TokenRelayRequestInterceptor
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的url connection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

resttemplate:
  sentinel:
    # 设置成false，表示关闭@SentinelRestTemplate注解
    enabled: true

jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600

mybatis:
  configuration:
    map-underscore-to-camel-case: true
