server:
  port: 8091

spring:
  application:
    name: weather-eureka-client

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/