server:
  port: 8092

spring:
  application:
    name: weather-report-eureka-feign-feign-gateway

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000