server:
  port: 8082

spring:
  application:
    name: weather-city-eureka

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
