server:
  port: 8085

spring:
  application:
    name: weather_eureka_client_feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000